/**
 * ONE-TIME extraction of the embedded datasets out of the original
 * kern-org-manager.html into this repo. Re-run only if the source app ships a
 * refreshed data drop.
 *
 *   bun run scripts/kern-extract-data.ts <path-to-kern-org-manager.html>
 *
 * Writes:
 *   src/lib/kern/data/seed.ts        SEED                      (committed)
 *   src/lib/kern/data/production.ts  PROD + the PROD_* series   (committed)
 *   src/lib/kern/data/roster.ts      TYROSTER                   (committed)
 *   public/kern/credit.json          CREDIT, borrower REDACTED  (gitignored)
 *
 * CREDIT.orgs[*].loans[*].b holds real borrower names ("LAST, FIRST") tied to
 * loan numbers — consumer NPI. It is display-only in the UI (see the port
 * design spec, Named deviations D2), so this script deletes it. The rest of the
 * dataset drives every number the Credit tab computes and is kept intact.
 */

import { readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'

const src = process.argv[2]
if (!src) {
  console.error('usage: bun run scripts/kern-extract-data.ts <kern-org-manager.html>')
  process.exit(1)
}

const html = readFileSync(src, 'utf8')
const lines = html.split('\n')

/** Pull `const NAME = <json>;` off the single line it occupies in the source. */
function grab(name: string): unknown {
  const line = lines.find((l) => l.startsWith(`const ${name} = `) || l.startsWith(`const ${name}=`))
  if (!line) throw new Error(`could not find "const ${name}" in ${src}`)
  const body = line.slice(line.indexOf('=') + 1).trim().replace(/;$/, '')
  return JSON.parse(body)
}

const root = resolve(import.meta.dirname, '..')
const banner = (what: string) =>
  `// GENERATED by scripts/kern-extract-data.ts from the original\n` +
  `// kern-org-manager.html. Do not hand-edit — re-run the script instead.\n` +
  `// ${what}\n\n`

// ---- seed: the starting org tree ------------------------------------------
const SEED = grab('SEED')
writeFileSync(
  resolve(root, 'src/lib/kern/data/seed.ts'),
  banner('Source line 227 — the initial org tree (divisions/regions/areas/branches/titles).') +
    `import type { SeedState } from '@/lib/kern/types'\n\n` +
    `export const SEED: SeedState = ${JSON.stringify(SEED, null, 1)} as SeedState\n`,
)

// ---- production series -----------------------------------------------------
const prod = {
  PROD: grab('PROD'),
  PROD_ASOF: grab('PROD_ASOF'),
  PROD_DAILY: grab('PROD_DAILY'),
  PROD_RUNRATE: grab('PROD_RUNRATE'),
  PROD_DAILY_BR: grab('PROD_DAILY_BR'),
  PROD_MBDAYS: grab('PROD_MBDAYS'),
}
writeFileSync(
  resolve(root, 'src/lib/kern/data/production.ts'),
  banner('Source lines 228-233 — monthly + intra-month production by branch.') +
    `import type {\n  ProductionMap,\n  DailySeries,\n  DailySeriesByBranch,\n  RunRate,\n} from '@/lib/kern/types'\n\n` +
    `export const PROD: ProductionMap = ${JSON.stringify(prod.PROD, null, 1)}\n\n` +
    `export const PROD_ASOF = ${JSON.stringify(prod.PROD_ASOF)}\n\n` +
    `export const PROD_DAILY: DailySeries = ${JSON.stringify(prod.PROD_DAILY, null, 1)}\n\n` +
    `export const PROD_RUNRATE: RunRate = ${JSON.stringify(prod.PROD_RUNRATE, null, 1)}\n\n` +
    `export const PROD_DAILY_BR: DailySeriesByBranch = ${JSON.stringify(prod.PROD_DAILY_BR, null, 1)}\n\n` +
    `export const PROD_MBDAYS: Record<string, number> = ${JSON.stringify(prod.PROD_MBDAYS, null, 1)}\n`,
)

// ---- Ty Kern roster --------------------------------------------------------
const TYROSTER = grab('TYROSTER')
writeFileSync(
  resolve(root, 'src/lib/kern/data/roster.ts'),
  banner('Source line 235 — the one-time Ty Kern division roster import.') +
    `import type { TyRoster } from '@/lib/kern/types'\n\n` +
    `export const TYROSTER: TyRoster = ${JSON.stringify(TYROSTER, null, 1)}\n`,
)

// ---- credit: REDACT borrower names, write outside the repo's git index -----
const CREDIT = grab('CREDIT') as {
  descs: string[]
  ops: string[]
  orgs: Record<string, { loans: Record<string, { b?: string; op?: number; i: unknown[][] }> }>
}
let redacted = 0
for (const org of Object.values(CREDIT.orgs)) {
  for (const loan of Object.values(org.loans)) {
    if (loan.b !== undefined) {
      delete loan.b
      redacted++
    }
  }
}
writeFileSync(resolve(root, 'public/kern/credit.json'), JSON.stringify(CREDIT))

console.log(`seed:        ${(SEED as { branches: unknown[] }).branches.length} branches`)
console.log(`production:  ${Object.keys(prod.PROD as object).length} orgs`)
console.log(`roster:      ${(TYROSTER as { people: unknown[] }).people.length} people`)
console.log(`credit:      ${Object.keys(CREDIT.orgs).length} orgs, ${redacted} borrower names REDACTED`)
